// ─────────────────────────────────────────────
// All copy, messages, and emoji sets in one place
// ─────────────────────────────────────────────

// Landing page rotating quotes
export const QUOTES = [
  "What did you do yesterday?",
  "Any blockers today?",
  "Keep it under 15 minutes.",
  "Ship it.",
  "Let's make it a good one.",
  "Coffee first, then standup.",
  "Done is better than perfect.",
  "Small steps, every day.",
  "What's blocking you?",
  "Focus on the outcome.",
  "Talk to each other, not the board.",
  "Async what you can, sync what you must.",
  "Yesterday, today, blockers. That's it.",
  "Make it count.",
  "Move fast, stand up, ship things.",
  "One task at a time.",
  "Clarity over cleverness.",
  "What would ship today?",
  "Leave the details for later.",
  "The sprint waits for no one.",
  "Progress, not perfection.",
  "No long stories. Just the facts.",
  "Be brief. Be brilliant. Be gone.",
  "What's the plan, team?",
  "Eyes on the board.",
  "Make today count.",
  "Stay focused, stay brief.",
  "What would you regret not shipping?",
  "Good morning. Let's build something.",
]

// Emoji sets by escalation level
export const EGGS = {
  mild:   ['👀', '🙄', '⏰', '🕐', '🥱', '😐', '🫠', '🤔', '🕰️'],
  medium: ['😴', '💤', '📢', '⚠️', '😬', '🔔', '😑', '🫥', '🤏'],
  spicy:  ['🚨', '😱', '🛑', '📣', '😮', '🙈', '😰', '🫣', '📯'],
  chaos:  ['🔥', '💀', '🤯', '😵‍💫', '🎺', '🆘', '💣', '🚒', '☎️', '🫨', '🧨', '🪦', '📉', '🆘'],
}

// Roast messages — 4 tiers from soft to brutal
export const ROASTS = {
  soft: [
    "Still going?",
    "Almost there… right?",
    "Wrapping up?",
    "No rush… 👀",
    "Take your time…",
    "Interesting. Go on.",
    "We're all ears.",
    "Mhm. And then?",
    "Last point, maybe?",
    "You doing okay up there?",
    "We're with you. Mostly.",
    "Setting a new personal best?",
    "Good start. Good. Start.",
    "Any day now…",
    "The team is listening. Actively.",
    "Don't mind us.",
  ],
  medium: [
    "Wrap it up 🎬",
    "TL;DR",
    "Have you tried bullet points?",
    "Coffee's getting cold ☕",
    "Anyone? Bueller?",
    "Plot twist: there is no blocker",
    "Speed run any%",
    "This meeting is loading…",
    "Somewhere a calendar invite just appeared.",
    "The clock is a social construct, and yet.",
    "Maybe just the highlights?",
    "Bold strategy. Let's see how it plays out.",
    "We appreciate the detail. Truly.",
    "Imagine this in async.",
    "There's a slack message for this.",
  ],
  hard: [
    "This could've been an email",
    "Is this a monologue or a standup?",
    "The team has left the chat",
    "404: brevity not found",
    "git commit -m 'stop talking'",
    "We've aged since this started",
    "The standup called. It wants to end.",
    "Your mic is definitely still on",
    "Somewhere, a sprint is dying.",
    "The board has not been updated.",
    "Jira just sent a passive-aggressive notification.",
    "This is a standup, not a TED talk.",
    "The backlog misses you.",
    "Productivity left the building.",
    "A standup within a standup.",
    "We started this meeting younger.",
  ],
  brutal: [
    "Narrator: they did not finish strong.",
    "Legend has it they're still talking",
    "Achievement unlocked: Oversharer 🏆",
    "This is fine 🔥",
    "New sprint just dropped",
    "Scrum master has entered the chat",
    "Sir, this is a Wendy's",
    "One more thing… (there is always one more thing)",
    "We believe in you. Please. Stop.",
    "ctrl + Z?",
    "The meeting that ate itself.",
    "History will remember this standup.",
    "Other teams have shipped already.",
    "The standup is now a sprint retrospective.",
    "At this point we might as well refine the backlog.",
    "Someone call a PM.",
    "Jeff from finance wants his day back.",
    "This was supposed to be a 15-minute meeting.",
    "We've entered uncharted territory.",
    "Please. For the love of agile.",
  ],
}

// Shown when a speaker finally stops after 3+ minutes
export const LONG_SPEAKER_REMARKS = [
  "And that's a wrap. Finally. 👏",
  "History has been made.",
  "Someone clip that.",
  "The legend leaves the stage.",
  "A moment of silence for everyone's time.",
  "That was a journey. Thank you for flying.",
  "New personal best. Impressive.",
  "The people have been heard. At length.",
  "We will not speak of this again.",
  "Archaeologists will study this standup.",
  "Worth every second. Probably.",
  "An instant classic.",
  "A slow clap somewhere in the distance.",
  "The sprint thanks you for your service.",
  "That's going in the retro.",
  "And scene. 🎬",
  "Certified moment.",
  "Respect. Misplaced, but present.",
  "The team survives.",
  "Future generations will learn from this.",
]

// End-of-standup verdict based on total duration
export const STANDUP_VERDICT = {
  // < 14 minutes
  fast: [
    "In and out. Respect. 🫡",
    "That's how it's done.",
    "Efficiency unlocked. 🏆",
    "Everyone gets 10 minutes back. You're welcome.",
    "Short standup, long sprint. Let's go.",
    "The team has entered the building and left.",
    "Legendary. Under budget, ahead of schedule.",
    "Under 14 minutes. This team understands.",
    "Crisp. Clean. Let's build.",
    "Standup speedrun complete.",
    "Minimal words, maximum impact.",
    "They said it couldn't be done. They were wrong.",
    "Back to work in record time.",
    "No time wasted. Many features incoming.",
  ],
  // 14–16 minutes
  perfect: [
    "Right on time. The dream team. ✦",
    "Textbook standup. Chef's kiss.",
    "15 minutes, exactly as the agile gods intended.",
    "Scrum master is crying tears of joy.",
    "This is what peak performance looks like.",
    "Nailed it. Same time tomorrow.",
    "The platonic ideal of a standup.",
    "Somewhere, a PM is printing this transcript.",
    "15 minutes well spent.",
    "Agile done right. Screenshot this.",
    "Precise. Purposeful. Productive.",
    "The benchmark. The standard. The legend.",
  ],
  // > 16 minutes
  long: [
    "A little over. We'll do better tomorrow. 😬",
    "16 minutes. The road to chaos begins here.",
    "Jeff from finance wants his Tuesday back.",
    "Next time: fewer words, same ideas.",
    "Time is a flat circle. This standup proved it.",
    "Somewhere, a product manager is updating the burndown chart.",
    "It's fine. Everything is fine. 🔥",
    "Could've been an email. But here we are.",
    "The retro writes itself.",
    "Next sprint: add 'be brief' to the definition of done.",
    "Minutes per person: a metric to investigate.",
    "The calendar says this ends. The team is not sure.",
    "Rome wasn't built in a day. This standup took longer.",
    "Tomorrow is a new opportunity for brevity.",
    "A learning experience. Expensive, but educational.",
  ],
}
